// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbContext.Migrations.MySqlDbContext
{
    [DbContext(typeof(MainDbContext.MySqlDbContext))]
    partial class MySqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FriendQuote", b =>
                {
                    b.Property<Guid>("FriendsFriendId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuotesQuoteId")
                        .HasColumnType("char(36)");

                    b.HasKey("FriendsFriendId", "QuotesQuoteId");

                    b.HasIndex("QuotesQuoteId");

                    b.ToTable("FriendQuote");
                });

            modelBuilder.Entity("Models.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Street")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Models.Friend", b =>
                {
                    b.Property<Guid>("FriendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("FriendId");

                    b.HasIndex("AddressId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("Models.Pet", b =>
                {
                    b.Property<Guid>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AnimalKind")
                        .HasColumnType("int");

                    b.Property<string>("AnimalKindString")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("AnimalMood")
                        .HasColumnType("int");

                    b.Property<string>("AnimalMoodString")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("OwnerFriendId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("PetId");

                    b.HasIndex("OwnerFriendId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Models.Quote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Author")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("QuoteText")
                        .HasColumnType("varchar(200)");

                    b.HasKey("QuoteId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("FriendQuote", b =>
                {
                    b.HasOne("Models.Friend", null)
                        .WithMany()
                        .HasForeignKey("FriendsFriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Quote", null)
                        .WithMany()
                        .HasForeignKey("QuotesQuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Friend", b =>
                {
                    b.HasOne("Models.Address", "Address")
                        .WithMany("Residents")
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Models.Pet", b =>
                {
                    b.HasOne("Models.Friend", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerFriendId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Models.Address", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("Models.Friend", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
